"""add_expenses_relation

Revision ID: 49c6e10c1c89
Revises: 5524ac05b751
Create Date: 2025-03-15 15:39:50.578570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c6e10c1c89'
down_revision: Union[str, None] = '5524ac05b751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('event_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'expense', 'event', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'event_id')
    # ### end Alembic commands ###
